name: Draft Release

on:
  workflow_dispatch:

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # IMPORTANT: ensures all tags are fetched

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod

      - name: Build project
        run: ./build.sh

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          name: "waybar-lyric ${{ env.tag }}"
          tag_name: "${{ env.tag }}"
          draft: true
          files: |
            build/*.tar.gz
            build/*.sha256
